server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: evaluation
          uri: lb://evaluation
          predicates:
            - Path=/api/v1/evaluations/**

        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api/v1/notifications/**

        - id: user
          uri: lb://user
          predicates:
            - Path=/microservice-user/users/**
          filters:
            - RewritePath=/microservice-user/users, /users

        - id: attendance
          uri: lb://attendance
          predicates:
            - Path=/api/v1/attendances/**

        - id: soporte
          uri: lb://soporte
          predicates:
            - Path=/microservice-soporte/soportes/**
          filters:
            - RewritePath=/microservice-soporte/soportes, /soportes

        - id: user-swagger
          uri: lb://user
          predicates:
            - Path=/user/v3/api-docs
          filters:
            - RewritePath=/user/v3/api-docs, /v3/api-docs
        - id: soporte-swagger
          uri: lb://soporte
          predicates:
            - Path=/soporte/v3/api-docs
          filters:
            - RewritePath=/soporte/v3/api-docs, /v3/api-docs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - url: /user/v3/api-docs
        name: User Microservice
      - url: /soporte/v3/api-docs
        name: Soporte Microservice

swagger:
  server-type: gateway