server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: evaluation
          uri: lb://evaluation
          predicates:
            - Path=/api/v1/evaluations/**

        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api/v1/notifications/**

        - id: user
          uri: lb://user
          predicates:
            - Path=/microservice-user/users/**
          filters:
            - RewritePath=/microservice-user/users, /users
        - id: speciality
          uri: lb://user
          predicates:
            - Path=/microservice-speciality/specialities/**
          filters:
            - RewritePath=/microservice-speciality/specialities, /specialities
        - id: coordinator
          uri: lb://user
          predicates:
            - Path=/microservice-coordinator/coordinators/**
          filters:
            - RewritePath=/microservice-coordinator/coordinators, /coordinators
        - id: student
          uri: lb://user
          predicates:
            - Path=/microservice-student/students/**
          filters:
            - RewritePath=/microservice-student/students, /students
        - id: teacher
          uri: lb://user
          predicates:
            - Path=/microservice-teacher/teachers/**
          filters:
            - RewritePath=/microservice-teacher/teachers, /teachers
        - id: medical-center
          uri: lb://user
          predicates:
            - Path=/microservice-medical-center/medical-centers/**
          filters:
            - RewritePath=/microservice-medical-center/medical-centers, /medical-centers

        - id: attendance
          uri: lb://attendance
          predicates:
            - Path=/microservice-attendance/attendances/**
          filters:
            - RewritePath=/microservice-attendance/attendances, /attendances
        - id: blockchain
          uri: lb://attendance
          predicates:
            - Path=/microservice-blockchain/blockchains/**
          filters:
            - RewritePath=/microservice-blockchain/blockchains, /blockchains

        - id: soporte
          uri: lb://soporte
          predicates:
            - Path=/microservice-soporte/soportes/**
          filters:
            - RewritePath=/microservice-soporte/soportes, /soportes

        - id: user-swagger
          uri: lb://user
          predicates:
            - Path=/user/v3/api-docs
          filters:
            - RewritePath=/user/v3/api-docs, /v3/api-docs
        - id: soporte-swagger
          uri: lb://soporte
          predicates:
            - Path=/soporte/v3/api-docs
          filters:
            - RewritePath=/soporte/v3/api-docs, /v3/api-docs
        - id: attendance-swagger
          uri: lb://attendance
          predicates:
            - Path=/attendance/v3/api-docs
          filters:
            - RewritePath=/attendance/v3/api-docs, /v3/api-docs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - url: /user/v3/api-docs
        name: User Microservice
      - url: /soporte/v3/api-docs
        name: Soporte Microservice
      - url: /attendance/v3/api-docs
        name: Attendance Microservice
