server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: evaluation
          uri: lb://evaluation
          predicates:
            - Path=/api/v1/evaluations/**
          filters:
            - name: CircuitBreaker
              args:
                name: evaluationServiceCircuitBreaker
                fallbackUri: forward:/evaluationFallback

        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationServiceCircuitBreaker
                fallbackUri: forward:/notificationFallback

        - id: users
          uri: lb://user
          predicates:
            - Path=/microservice-user/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/userFallback
            - RewritePath=/microservice-user/users, /users

        - id: attendance
          uri: lb://attendance
          predicates:
            - Path=/api/v1/attendances/**
          filters:
            - name: CircuitBreaker
              args:
                name: attendanceServiceCircuitBreaker
                fallbackUri: forward:/attendanceFallback

        - id: soporte
          uri: lb://soporte
          predicates:
            - Path=/api/v1/soportes/**
          filters:
            - name: CircuitBreaker
              args:
                name: soporteServiceCircuitBreaker
                fallbackUri: forward:/soporteFallback

        - id: user-swagger
          uri: lb://user
          predicates:
            - Path=/user/v3/api-docs
          filters:
            - RewritePath=/user/v3/api-docs, /v3/api-docs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - url: /user/v3/api-docs
        name: User Microservice

resilience4j.circuitbreaker:
  instances:
    evaluationServiceCircuitBreaker:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
    notificationServiceCircuitBreaker:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
    userServiceCircuitBreaker:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
    attendanceServiceCircuitBreaker:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
    soporteServiceCircuitBreaker:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
