server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productServiceCircuitBreaker
                fallbackUri: forward:/productFallback

        - id: cart
          uri: lb://cart
          predicates:
            - Path=/api/v1/carts/**
          filters:
            - name: CircuitBreaker
              args:
                name: cartServiceCircuitBreaker
                fallbackUri: forward:/cartFallback

        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/userFallback

        - id: orders
          uri: lb://orders
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/orderFallback

        - id: trip
          uri: lb://trip
          predicates:
            - Path=/api/v1/trips/**
          filters:
            - name: CircuitBreaker
              args:
                name: tripServiceCircuitBreaker
                fallbackUri: forward:/tripFallback

resilience4j.circuitbreaker:
  instances:
    productServiceCircuitBreaker:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
    cartServiceCircuitBreaker:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
    userServiceCircuitBreaker:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
    orderServiceCircuitBreaker:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
    tripServiceCircuitBreaker:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
